-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_BN017_CLASSE]'))
DROP VIEW [dbo].[VW_BN017_CLASSE]
GO

-- Cria View
CREATE VIEW [dbo].[VW_BN017_CLASSE]
WITH ENCRYPTION
AS
  SELECT
  
  BN017_NR_SECAO,
  BN017_NR_CLASSE

FROM 	BN017 

GROUP BY
BN017_NR_SECAO,
BN017_NR_CLASSE
