-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_CB001_PP]'))
DROP VIEW [dbo].[VW_CB001_PP]
GO

-- Tela Cliente - Posição de Titulos
-- Cria View
CREATE VIEW [dbo].[VW_CB001_PP]
WITH ENCRYPTION
AS
SELECT
  CB001_NR_INST,
  CB001_NR_PROTOC,
  CASE 
    WHEN LEN(CONVERT(NUMERIC, CB001_NR_IDENT1)) = 9  THEN '00' + CONVERT(VARCHAR, CONVERT(NUMERIC, CB001_NR_IDENT1))
    WHEN LEN(CONVERT(NUMERIC, CB001_NR_IDENT1)) = 10 THEN '0' + CONVERT(VARCHAR, CONVERT(NUMERIC, CB001_NR_IDENT1))
    WHEN LEN(CONVERT(NUMERIC, CB001_NR_IDENT1)) = 11 THEN CONVERT(VARCHAR, CONVERT(NUMERIC, CB001_NR_IDENT1))
    WHEN LEN(CONVERT(NUMERIC, CB001_NR_IDENT1)) = 13 THEN '0' + CONVERT(VARCHAR, CONVERT(NUMERIC, CB001_NR_IDENT1))
    ELSE CONVERT(VARCHAR, CONVERT(NUMERIC, CB001_NR_IDENT1))
  END CB001_NR_IDENT1,
  CB001_NR_IDENT2,
  CB001_NR_IDENT3,
  CB001_DT_REF   ,
  CB001_CD_PUBLIC,
  CB060_DS_PUBLIC,
  CASE 
    WHEN CB060_TP_DOC = 1 THEN 'Desmonstrativo'
    WHEN CB060_TP_DOC = 2 THEN 'Cobrança'
    ELSE 'Indefinido'
  END CB060_TP_DOC
FROM
  CB001,
  CB850,
  CB060
WHERE
/*
    (@ENT_NR_INST   IS NULL OR CB001_NR_INST   = @ENT_NR_INST)
AND (@ENT_NR_CPFCNPJ IS NULL OR CONVERT(NUMERIC, CB001_NR_IDENT1) = @ENT_NR_CPFCNPJ)
*/
/* CB001 -> CB850 */
CB001_NR_PROTOC = CB850_NR_PROTOC
/* CB001 -> CB060 */
AND CB001_NR_INST   = CB060_NR_INST
AND CB001_CD_EMIEMP = CB060_CD_EMIEMP
AND CB001_CD_PUBLIC = CB060_CD_PUBLIC
AND CB001_ID_SITUAC <> 90 /* não traz lote cancelado */

GO