-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_CB208_FLUXO_DIARIO]'))
DROP VIEW [dbo].[VW_CB208_FLUXO_DIARIO]
GO

-- Carteira - Fluxo Di�rio 
-- Cria View
CREATE VIEW [dbo].[VW_CB208_FLUXO_DIARIO]
WITH ENCRYPTION
AS
 SELECT 
  CB208_NR_OPERADOR,
  CB208_NR_CEDENTE,
  CB053_DS_EMIEMP,
  CB208_DT_MOVTO ,
  SUM(CB208_VL_TOTDIA) CB208_VL_TOTDIA,
  SUM(CB208_VL_CATPRO) CB208_VL_CATPRO,
  SUM(CB208_VL_CATCED) CB208_VL_CATCED,
  SUM(CB208_QT_TOTAL) CB208_QT_TOTAL  
FROM CB208
LEFT JOIN CB053
ON  CB053_NR_INST	= CB208_NR_OPERADOR   
AND CB053_CD_EMIEMP = CB208_NR_CEDENTE 
GROUP BY 
  CB208_DT_MOVTO ,
  CB208_NR_OPERADOR,
  CB208_NR_CEDENTE,
  CB053_DS_EMIEMP

 
GO

