-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_CB213_AI]'))
DROP VIEW [dbo].[VW_CB213_AI]
GO

-- Tela PUBLISH - Atendimento -� Inconsist�ncias
-- Cria View
CREATE VIEW [dbo].[VW_CB213_AI]
WITH ENCRYPTION
AS

SELECT 
  CB213_NR_CONTRA,
  CB213_DT_LIBERA,
  CB213_NM_CLIENT,
  CONVERT(VARCHAR(3), CB213_NR_DDD1) + '-' + CONVERT(VARCHAR(9), CB213_NR_FONE1) CB213_NR_FONE1,
  CONVERT(VARCHAR(3), CB213_NR_DDD2) + '-' + CONVERT(VARCHAR(9), CB213_NR_FONE2) CB213_NR_FONE2,
  CB213_DS_LOGRAD,
  CB213_NR_LOGRAD,
  CB213_DS_COMLGR,
  CB213_DS_BAIRRO,
  CB213_NM_CIDADE,
  CB213_SG_UF    ,
  CB213_CD_CEP   ,
  --CB213_ID_MTVDEV,
  CASE 
  	WHEN CB213_ID_MTVDEV = 1 THEN 'Mudou-se'
	WHEN CB213_ID_MTVDEV = 2 THEN 'Endereço insuficiente'
	WHEN CB213_ID_MTVDEV = 3 THEN 'Não existe o numero indicado'
	WHEN CB213_ID_MTVDEV = 4 THEN 'Falecido'
	WHEN CB213_ID_MTVDEV = 5 THEN 'Desconhecido'
	WHEN CB213_ID_MTVDEV = 6 THEN 'Recusado'
	WHEN CB213_ID_MTVDEV = 7 THEN 'Ausente'
	WHEN CB213_ID_MTVDEV = 8 THEN 'Não procurado'
	WHEN CB213_ID_MTVDEV = 9 THEN 'Outros'
	WHEN CB213_ID_MTVDEV = 100 THEN 'Cep invalido'
	WHEN CB213_ID_MTVDEV = 101 THEN 'CEP x Estado inválido'
	WHEN CB213_ID_MTVDEV = 102 THEN 'Dados do endereço faltante'
	ELSE 'Indefinido'
	END CB213_ID_MTVDEV,
  CB213_NR_CPFCNPJ,
  CB213_ID_ERREND,
  CB215_NR_FAC,
  CB213_DT_SOLUC
FROM
  CB213 LEFT JOIN CB215 ON (
          CB213_NR_OPERADOR = CB215_NR_OPERADOR
      AND CB213_NR_CEDENTE  = CB215_NR_CEDENTE
	  AND CB213_NR_CONTRA   = CB215_NR_CONTRA
  )
  /*
WHERE
/* CB213 -> CB215 */
    (@ENT_NR_CPFCNPJ IS NULL OR CB213_NR_CPFCNPJ = @ENT_NR_CPFCNPJ)
AND (@ENT_NR_CONTRA  IS NULL OR CB213_NR_CONTRA  = @ENT_NR_CONTRA)
AND (@ENT_ID_MTVDEV  IS NULL OR CB213_ID_MTVDEV  = @ENT_ID_MTVDEV)
AND (@ENT_DT_INI     IS NULL OR CB213_DT_LIBERA BETWEEN @ENT_DT_INI AND @ENT_DT_FIM)  
--AND CB213_ID_ERREND > 1 /* COM ERRO NO END. */
AND (@ENT_NR_CIF  IS NULL OR CB215_NR_FAC = @ENT_NR_CIF)
AND (@ENT_NR_LOTE IS NULL OR CB215_NR_LOTE = @ENT_NR_LOTE)
AND (@ENT_DT_INI_RES IS NULL OR CB213_DT_SOLUC BETWEEN @ENT_DT_INI_RES AND @ENT_DT_FIM_RES)  
AND (CB213_ID_ERREND  = @ENT_ID_ERREND)
*/