-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_CB201_SACADO]'))
  DROP VIEW [dbo].[VW_CB201_SACADO]
GO

-- Posição de títulos
-- Cria View
CREATE VIEW [dbo].[VW_CB201_SACADO]
WITH ENCRYPTION
AS
  SELECT DISTINCT
    --TOP 5000 -- FAKE :(
    CB201_NR_OPERADOR,
    CB201_NR_CEDENTE,
    CB201_NR_CPFCNPJ,  
    CB201_NM_NMSAC,
    CB201_NR_DDD,
    CB201_NR_CEL,
    CB201_NM_EMAIL
  FROM
    CB201
GO