-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_EM055]'))
DROP VIEW [dbo].[VW_EM055]
GO

-- Criar View da tela - EMAIL - Configurações -  Código EMAIL
CREATE VIEW [dbo].[VW_EM055]
WITH ENCRYPTION
AS

SELECT
  EM055_NR_INST,
  EM055_CD_EMIEMP,
  EM055_CD_CODEMAIL,
  EM055_DS_CODEMAIL,
  EM055_ID_ATIVO ,
  EM055_TP_CATEG,
  EM055_CD_OPESIS,
  EM055_DT_INCSIS,
  EM055_DT_ATUSIS,

  -- INSTITUICAO
  CB050_NM_INST,
  -- EMISSOR
  CB053_CD_EMIEMP,
  CB053_DS_EMIEMP
  
FROM
  EM055

INNER JOIN CB050 -- INSTITUICAO
ON  CB050_NR_INST = EM055_NR_INST

INNER JOIN CB053 -- EMISSOR
ON  CB053_NR_INST = EM055_NR_INST
AND CB053_CD_EMIEMP = EM055_CD_EMIEMP
  
GO
