-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_EM061]'))
DROP VIEW [dbo].[VW_EM061]
GO

-- Cria View da tela EMAIL - Configurações -  Mensagem EMAIL
CREATE VIEW [dbo].[VW_EM061]
WITH ENCRYPTION
AS

SELECT
  EM061_NR_INST  ,
  CB050_NM_INST,
  EM061_CD_EMIEMP,
  EM061_CD_CODEMAIL,
  EM061_DS_TEXTO ,   
  EM061_ID_ATIVO ,
  EM061_ID_ATIVO_label = CASE EM061_ID_ATIVO
    WHEN 1 THEN 'Ativo'      
    ELSE 'Inativo'
  END,    
  EM061_ID_STATUS,
  EM061_ID_STATUS_label = CASE EM061_ID_STATUS
    WHEN 1 THEN 'Pendente'      
    ELSE 'Aprovada'
  END,    
  EM061_CD_OPESIS,
  EM061_DT_INCSIS,
  EM061_DT_ATUSIS,

  -- EMISSOR
  CB053_CD_EMIEMP,
  CB053_DS_EMIEMP,
  --CODIGO EMAIL
  EM055_CD_CODEMAIL,
  EM055_DS_CODEMAIL
	
FROM
  EM061

INNER JOIN CB050 -- EMISSOR
ON	CB050_NR_INST	= EM061_NR_INST


INNER JOIN CB053 -- EMISSOR
ON	CB053_NR_INST	= EM061_NR_INST
AND	CB053_CD_EMIEMP = EM061_CD_EMIEMP

INNER JOIN EM055 -- CODIGO EMAIL
ON	EM055_NR_INST	= EM061_NR_INST
AND	EM055_CD_EMIEMP = EM061_CD_EMIEMP
AND EM055_CD_CODEMAIL = EM061_CD_CODEMAIL
  
GO
