 -- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_EM065]'))
DROP VIEW [dbo].VW_EM065
GO

-- Criar View da tela - SMS - Configurações - Blacklist
CREATE VIEW [dbo].VW_EM065
WITH ENCRYPTION
AS

SELECT
  EM065_NR_INST   ,
  CB050_NM_INST   ,
  EM065_DS_EMAIL, 
  EM065_NR_CPFCNPJ,
  EM065_ID_MOTIVO ,
  EM065_CD_OPESIS ,
  EM065_DT_INCSIS ,
  EM065_DT_ATUSIS
FROM
  EM065,
  CB050
WHERE
  EM065_NR_INST = CB050_NR_INST

GO