-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_MG055]'))
DROP VIEW [dbo].[VW_MG055]
GO

-- Criar View da tela - SMS - Configurações -  Código SMS
CREATE VIEW [dbo].[VW_MG055]
WITH ENCRYPTION
AS

SELECT
  MG055_NR_INST,
  MG055_CD_EMIEMP,
  MG055_CD_CODSMS,
  MG055_DS_CODSMS,
  MG055_ID_ATIVO ,
  MG055_TP_CATEG,
  MG055_CD_OPESIS,
  MG055_DT_INCSIS,
  MG055_DT_ATUSIS,

  -- INSTITUICAO
  CB050_NM_INST,
  -- EMISSOR
  CB053_CD_EMIEMP,
  CB053_DS_EMIEMP
  
FROM
  MG055

INNER JOIN CB050 -- INSTITUICAO
ON  CB050_NR_INST = MG055_NR_INST

INNER JOIN CB053 -- EMISSOR
ON  CB053_NR_INST = MG055_NR_INST
AND CB053_CD_EMIEMP = MG055_CD_EMIEMP
  
GO
