 -- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apagar view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_MG000]'))
DROP VIEW [dbo].VW_MG000
GO

CREATE VIEW [dbo].VW_MG000
WITH ENCRYPTION
AS

SELECT
  MG000_NR_INST  ,
  CB050_NM_INST  ,
  MG000_QT_DIAS  ,
  MG000_QT_MSG   ,
  MG000_PC_PROPOR,
  MG000_CD_OPESIS,
  MG000_DT_INCSIS,
  MG000_DT_ATUSIS
FROM
  MG000,
  CB050
WHERE
  MG000_NR_INST = CB050_NR_INST


GO