 -- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_MG070]'))
DROP VIEW [dbo].VW_MG070
GO

-- Criar View da tela - SMS - Configurações - Pacote
CREATE VIEW [dbo].VW_MG070
WITH ENCRYPTION
AS

SELECT
  MG070_NR_OPERADOR,
  --MG070_NR_CEDENTE,
  CB050_NM_INST  ,
  --CB053_DS_EMIEMP,
  MG070_NR_PACOTE,
  MG070_NM_PACOTE,
  MG070_CD_OPESIS,
  MG070_DT_INCSIS,
  MG070_DT_ATUSIS
FROM
  MG070
INNER JOIN CB050
ON CB050_NR_INST = MG070_NR_OPERADOR

/*INNER JOIN CB053
ON CB053_NR_INST = MG070_NR_OPERADOR
AND CB053_CD_EMIEMP = MG070_NR_CEDENTE*/
  
GO