 -- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apagar view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_MG050]'))
DROP VIEW [dbo].VW_MG050
GO

-- Criar View da tela - SMS - Configura��es -� C�digo SMS
CREATE VIEW [dbo].VW_MG050
WITH ENCRYPTION
AS

SELECT
  MG050_NR_OPERADOR,
  MG050_NR_CEDENTE, 
  MG050_NR_BROKER,
  MG050_NM_BROKER,
  MG050_NR_PORCEN,
  MG050_ID_ATIVO ,
  MG050_ID_ATIVO_label = CASE MG050_ID_ATIVO
    WHEN 1 THEN 'Ativo'
    ELSE 'Inativo'
  END,
  MG050_CD_OPESIS,
  MG050_DT_INCSIS,
  MG050_DT_ATUSIS
FROM
  MG050

GO