-- Configura View
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga view
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_MG061]'))
DROP VIEW [dbo].[VW_MG061]
GO

-- Cria View da tela SMS - Configurações -  Mensagem SMS
CREATE VIEW [dbo].[VW_MG061]
WITH ENCRYPTION
AS

SELECT
  MG061_NR_INST  ,
  CB050_NM_INST,
  MG061_CD_EMIEMP,
  MG061_CD_CODSMS,
  MG061_DS_TEXTO , 
  MG061_QT_CARACT,
  MG061_ID_ATIVO ,
  MG061_ID_ATIVO_label = CASE MG061_ID_ATIVO
    WHEN 1 THEN 'Ativo'      
    ELSE 'Inativo'
  END,    
  MG061_ID_STATUS,
  MG061_ID_STATUS_label = CASE MG061_ID_STATUS
    WHEN 1 THEN 'Pendente'      
    ELSE 'Aprovada'
  END,    
  MG061_CD_OPESIS,
  MG061_DT_INCSIS,
  MG061_DT_ATUSIS,

  -- EMISSOR
  CB053_CD_EMIEMP,
  CB053_DS_EMIEMP,
  --CODIGO SMS
  MG055_CD_CODSMS,
  MG055_DS_CODSMS
	
FROM
  MG061

INNER JOIN CB050 -- EMISSOR
ON	CB050_NR_INST	= MG061_NR_INST


INNER JOIN CB053 -- EMISSOR
ON	CB053_NR_INST	= MG061_NR_INST
AND	CB053_CD_EMIEMP = MG061_CD_EMIEMP

INNER JOIN MG055 -- CODIGO SMS
ON	MG055_NR_INST	= MG061_NR_INST
AND	MG055_CD_EMIEMP = MG061_CD_EMIEMP
AND MG055_CD_CODSMS = MG061_CD_CODSMS
  
GO
