-- Configura Procedure
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

-- Apaga Procedure
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_BALANCETE]') AND type in (N'P', N'PC'))
DROP PROCEDURE  [dbo].[SP_BALANCETE]
GO

-- Cria Procedure
CREATE PROCEDURE [dbo].[SP_BALANCETE]
/*:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  :: EMPRESA    : IMSTECH                                                      ::
  :: SISTEMA    : DPGE2                                                        ::
  :: MÓDULO     : Balancete diário                                             ::
  :: OBSERVAÇÃO :                                                              ::
  ::---------------------------------------------------------------------------::
  :: PROGRAMADOR:                                                              ::
  :: DATA       :                                              VERSÃO SP:      ::
  :: ALTERAÇÃO  :                                                              ::
  ::---------------------------------------------------------------------------::
  :: PROGRAMADOR: Fábio Bernardo                                               ::
  :: DATA       : 15/02/2013                                                   ::
  :: ALTERAÇÃO  : Nova coluna 7 - Devolução por Aditamento                     ::
  ::---------------------------------------------------------------------------::
  :: PROGRAMADOR: Fábio Bernardo                                               ::
  :: DATA       : 02/01/2013                                                   ::
  :: ALTERAÇÃO  : Atualização BN_DPGE , antiga SP0305017                       ::
  ::---------------------------------------------------------------------------::
  :: PROGRAMADOR: Felipe Cesarini                                              ::
  :: DATA       : 05/05/2011                                   VERSÃO SP:    1 ::
  :: ALTERAÇÃO  : Primeira versão                                              ::
  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*/
  /*-------------------------------------------------------------------------------
  DESCRIÇÃO DA FUNCIONALIDADE:

  Balancete diário
  -------------------------------------------------------------------------------*/
  @ENT_NR_VRS    VARCHAR(4)   ,       /* ENTRADA DA VERSAO DO MODULO             */
  @ENT_NR_GRUPO  NUMERIC(8,0) ,       /* Nr. instituição                         */
  @ENT_NR_INST   NUMERIC(8,0) ,       /* Nr. emissor/empresa                     */
  @ENT_NR_PROD 	 NUMERIC(5,0) ,       /* Nr. Produto                             */
  @ENT_NR_BANCO NUMERIC(5,0) ,       /* Nr. Banco                               */
  @ENT_NR_AGENC  NUMERIC(5,0) ,       /* Agência                                 */
  @ENT_NR_CONTA  NUMERIC(12,0),       /* Nr. conta                               */
  @ENT_DT_INI    NUMERIC(8,0) ,       /* Dt. Movto. Ini.                         */
  @ENT_NR_USR    NUMERIC(9)           /* Nr. do usuário                          */
  WITH ENCRYPTION
AS
/*--------------------------------------------------------------------------*/
/* Verifica se a versão do Módulo é diferente da versão da Stored Procedure */
/*--------------------------------------------------------------------------*/
--DECLARE @LOC_NR_RTCODE INTEGER
--EXECUTE @LOC_NR_RTCODE = SP_CD0100002 @ENT_NR_VRS, '1', 'SP_CB0305017'
--IF @LOC_NR_RTCODE = 99999 RETURN 99999
/*--------------------------------------------------------------------------*/
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS OFF

CREATE TABLE #TB05017 (
  BN402_NR_PROD NUMERIC(5)   ,
  BN004_NM_PROD   VARCHAR(40)  ,
  BN402_DT_MOVTO  NUMERIC(8)   , 
  BN402_VL_VALOR1 NUMERIC(17,2),  -- 1- SALDO ANTERIOR
  BN402_QT_TOTAL1 NUMERIC(9)   ,
  BN402_VL_VALOR2 NUMERIC(17,2),  -- 2- ENTRADA
  BN402_QT_TOTAL2 NUMERIC(9)   ,
  BN402_VL_VALOR3 NUMERIC(17,2),  -- 3- LIQUIDADOS 
  BN402_QT_TOTAL3 NUMERIC(9)   , 
  BN402_VL_VALOR4 NUMERIC(17,2),  -- 4- BAIXA POR SOLICITACAO
  BN402_QT_TOTAL4 NUMERIC(9)   ,
  BN402_VL_VALOR5 NUMERIC(17,2),  -- 5- BAIXA POR DECURSO DE PRAZO
  BN402_QT_TOTAL5 NUMERIC(9),
  BN402_VL_VALOR6 NUMERIC(17,2),  -- 6- DEVOLUCAO POR REJEICAO 
  BN402_QT_TOTAL6 NUMERIC(9),
  BN402_VL_VALOR7 NUMERIC(17,2),  -- 7- DEVOLUCAO POR ADITAMENTO
  BN402_QT_TOTAL7 NUMERIC(9),
  BN402_VL_VALOR8 NUMERIC(17,2),  -- 8- BAIXA POR VENCIMENTO
  BN402_QT_TOTAL8 NUMERIC(9),
  BN402_VL_VALOR10 NUMERIC(17,2), -- 10- SALDO ATUAL
  BN402_QT_TOTAL10 NUMERIC(9)

)  

/* 1 -SALDO ANTERIOR */
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR1,
  BN402_QT_TOTAL1
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_PROD   IS NULL OR BN402_NR_PROD   = @ENT_NR_PROD)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 1 /* SALDO ANTERIOR */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))



GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 
  
  
  
  
  
  

/* 2 - ENTRADAS */
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR2,
  BN402_QT_TOTAL2
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD   IS NULL OR BN402_NR_PROD   = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 2 /* ENTRADAS */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 
  
  
  
  
  
  
/* 3 - LIQUIDADOS */
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR3,
  BN402_QT_TOTAL3
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD   IS NULL OR BN402_NR_PROD   = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 3 /* LIQUIDADOS */ 
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 






/* 4 - BAIXA POR SOLICITACAO */  
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR4,
  BN402_QT_TOTAL4
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD   IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 4 /* 4- Baixa solicitada  */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 








/* 5 - BAIXA POR DECURSO DE PRAZO */  
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR5,
  BN402_QT_TOTAL5
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 5 /* 5- Baixa solicitada  */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 








/* 6 - DEVOLUCAO POR REJEICAO */  
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR6,
  BN402_QT_TOTAL6
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 6 /*  DEVOLUCAO POR REJEICAO  */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 








/* 7 - DEVOLUCAO POR ADITAMENTO */  
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR7,
  BN402_QT_TOTAL7
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 7 /*  DEVOLUCAO POR ADITAMENTO */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 


/* 8 - BAIXA POR VENCIMENTO */  
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR8,
  BN402_QT_TOTAL8
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 8 /*  BAIXA POR VENCIMENTO */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 











/* SALDO ATUAL */
INSERT INTO #TB05017 (
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  BN402_VL_VALOR10,
  BN402_QT_TOTAL10
)
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUM(BN402_VL_VALOR),
  SUM(BN402_QT_TOTAL)
FROM
  BN402,
  BN004
WHERE
    (@ENT_NR_GRUPO   IS NULL OR BN402_NR_GRUPO   = @ENT_NR_GRUPO)
AND (@ENT_NR_INST IS NULL OR BN402_NR_INST = @ENT_NR_INST)
AND (@ENT_NR_BANCO IS NULL OR BN402_NR_BANCO = @ENT_NR_BANCO)
AND (@ENT_NR_AGENC  IS NULL OR BN402_NR_AGENC  = @ENT_NR_AGENC )
AND (@ENT_NR_CONTA  IS NULL OR BN402_NR_CONTA  = @ENT_NR_CONTA )
AND (@ENT_NR_PROD IS NULL OR BN402_NR_PROD = @ENT_NR_PROD)
AND (@ENT_DT_INI    IS NULL OR BN402_DT_MOVTO  = @ENT_DT_INI)  
/* BN402 -> BN004 */
AND BN402_NR_PROD = BN004_NR_PROD
AND BN402_TP_ACUM = 10 /* SALDO ATUAL */
AND ((@ENT_NR_USR IS NULL) OR EXISTS (  
  SELECT  
    BN013_NR_GRUPO  
  FROM  
    BN013  
  WHERE  
      BN013_NR_USR    = @ENT_NR_USR
  AND BN013_NR_GRUPO   = BN402_NR_GRUPO  
  AND BN013_NR_INST = BN402_NR_INST  
))

GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO 
  
  
  
  
  
  
  
  
  
  
  
/* RESULT SET */ 
SELECT
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO ,
  SUBSTRING(Cast(BN402_DT_MOVTO as varchar),7,2)+'/'+SUBSTRING(Cast(BN402_DT_MOVTO as varchar),5,2)+'/'+SUBSTRING(Cast(BN402_DT_MOVTO as varchar),1,4) AS BN402_DT_MOVTO_DD_MM_YYYY,
  SUM(BN402_VL_VALOR1)  BN402_VL_VALOR1,
  SUM(BN402_QT_TOTAL1)  BN402_QT_TOTAL1,
  SUM(BN402_VL_VALOR2)  BN402_VL_VALOR2,
  SUM(BN402_QT_TOTAL2)  BN402_QT_TOTAL2,
  SUM(BN402_VL_VALOR3)  BN402_VL_VALOR3,
  SUM(BN402_QT_TOTAL3)  BN402_QT_TOTAL3,
  SUM(BN402_VL_VALOR4)  BN402_VL_VALOR4,
  SUM(BN402_QT_TOTAL4)  BN402_QT_TOTAL4,
  SUM(BN402_VL_VALOR5)  BN402_VL_VALOR5,
  SUM(BN402_QT_TOTAL5)  BN402_QT_TOTAL5,
  SUM(BN402_VL_VALOR6)  BN402_VL_VALOR6,
  SUM(BN402_QT_TOTAL6)  BN402_QT_TOTAL6,
  SUM(BN402_VL_VALOR7)  BN402_VL_VALOR7,
  SUM(BN402_QT_TOTAL7)  BN402_QT_TOTAL7,
  SUM(BN402_VL_VALOR8)  BN402_VL_VALOR8,
  SUM(BN402_QT_TOTAL8)  BN402_QT_TOTAL8,
  SUM(BN402_VL_VALOR10) BN402_VL_VALOR10,
  SUM(BN402_QT_TOTAL10) BN402_QT_TOTAL10
FROM
  #TB05017
GROUP BY 
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO
ORDER BY
  BN402_NR_PROD,
  BN004_NM_PROD  ,
  BN402_DT_MOVTO   



SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON
/*-------------------------------------------------------------------------------
  RESULT SET:

  BN402_NR_PROD
  BN004_NM_PROD  
  BN402_DT_MOVTO
  BN402_VL_VALOR
  BN402_QT_TOTAL
-------------------------------------------------------------------------------*/

GO


