

-- Configura Procedure
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


-- Apaga Procedure
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_CF_PREPARA_MATRICULAS]') AND type in (N'P', N'PC'))
DROP PROCEDURE  [dbo].[SP_CF_PREPARA_MATRICULAS]
GO


CREATE PROCEDURE [dbo].[SP_CF_PREPARA_MATRICULAS]
@NR_BANCO INT, @NOMEARQ VARCHAR(255), @NR_ENT INT
WITH ENCRYPTION
AS
DECLARE @NR_CONTRA VARCHAR(40)
DECLARE @LFAZ BIT
DECLARE @LACHOU BIT

SET @LFAZ = 1

DECLARE @KNSEQ INT, @KMATRIC VARCHAR(40), @KMATRIC2 VARCHAR(40)

-- CASO ARQUIVO FOR DE MATRICULA
DECLARE NAVEGA_ CURSOR LOCAL FAST_FORWARD FOR
select A.NSEQ,  RTRIM(LTRIM(A.NR_MATRIC))
from CF_001 A
WHERE A.NOMEARQ=@NOMEARQ AND @NR_BANCO=@NR_BANCO 
      AND ISNULL(A.NR_CONTRA,'') = '' 
      AND ISNULL(A.NR_CNPJ,0)    = 0
      AND ISNULL(NR_MATRIC,'') <>  ''
      AND A.TPBAIXACFP=0
	  AND A.NR_ENT = @NR_ENT
OPEN NAVEGA_
FETCH NEXT FROM NAVEGA_
INTO @KNSEQ, @KMATRIC
WHILE @@FETCH_STATUS = 0
BEGIN

  SET @LACHOU=0  
  DECLARE NAVEGA_1 CURSOR LOCAL FAST_FORWARD FOR
  SELECT DBO.CF_PADLEFT( 40, RTRIM(LTRIM(BKN025_NR_MATRIC)), '@' ), BKN025_NR_CONTRA
  FROM BKN025 
  WHERE BKN025_NR_BANCO=@NR_BANCO AND BKN025_NR_MATRIC LIKE '%'+@KMATRIC+'%' 
  OPEN NAVEGA_1
  FETCH NEXT FROM NAVEGA_1
  INTO @KMATRIC2, @NR_CONTRA
  WHILE @@FETCH_STATUS = 0 AND @LFAZ=1
  BEGIN
    IF( @KMATRIC2 = DBO.CF_PADLEFT( 40, RTRIM(LTRIM(@KMATRIC)), '@' ) )
    BEGIN
      SET @LACHOU=1
      UPDATE CF_001
      SET NR_CONTRA=@NR_CONTRA
      WHERE NSEQ=@KNSEQ
    END
    
    FETCH NEXT FROM NAVEGA_1
    INTO @KMATRIC2,  @NR_CONTRA
  END  
  CLOSE NAVEGA_1
  DEALLOCATE  NAVEGA_1
  
  IF( @LACHOU = 0 )
  BEGIN
    UPDATE CF_001
    SET TPBAIXACFP=15, OBS='CONTRATO NÃO encontrado pela MATRÍCULA'
    WHERE NSEQ=@KNSEQ
  END    
  
  FETCH NEXT FROM NAVEGA_
  INTO @KNSEQ, @KMATRIC
END  
CLOSE NAVEGA_
DEALLOCATE  NAVEGA_

GO


